default: &default
  adapter: sqlite3
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite

test:
  <<: *default
  database: db/test.sqlite

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: gift_giver
  host: localhost
  pool: 5
  timeout: 5000
